package cn.com.qytx.webservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CardService", targetNamespace = "http://server.wei.com")
public interface CardService {
	String USERSTR = "user";
	String PASS = "pass";
	String targetNamespaceStr = "http://server.wei.com";
	String  ACB301= "aab301";
	String  ACC002= "aac002";
	String  ACC003= "aac003";
	/**
	 * 
	 * @param aac003
	 * @param aab301
	 * @param aaz500
	 * @param user
	 * @param aac002
	 * @param pass
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "getCardReturn", targetNamespace = targetNamespaceStr)
	@RequestWrapper(localName = "getCard", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.GetCard")
	@ResponseWrapper(localName = "getCardResponse", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.GetCardResponse")
	String getCard(
			@WebParam(name = USERSTR, targetNamespace = targetNamespaceStr) String user,
			@WebParam(name = PASS, targetNamespace = targetNamespaceStr) String pass,
			@WebParam(name = "aaz500", targetNamespace = targetNamespaceStr) String aaz500,
			@WebParam(name = ACC002, targetNamespace = targetNamespaceStr) String aac002,
			@WebParam(name = ACC003, targetNamespace = targetNamespaceStr) String aac003,
			@WebParam(name = ACB301, targetNamespace = targetNamespaceStr) String aab301);

	/**
	 * 
	 * @param aac003
	 * @param aab301
	 * @param user
	 * @param aac002
	 * @param pass
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "getBankReturn", targetNamespace = targetNamespaceStr)
	@RequestWrapper(localName = "getBank", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.GetBank")
	@ResponseWrapper(localName = "getBankResponse", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.GetBankResponse")
	String getBank(
			@WebParam(name = USERSTR, targetNamespace = targetNamespaceStr) String user,
			@WebParam(name = PASS, targetNamespace = targetNamespaceStr) String pass,
			@WebParam(name = ACC002, targetNamespace = targetNamespaceStr) String aac002,
			@WebParam(name = ACC003, targetNamespace = targetNamespaceStr) String aac003,
			@WebParam(name = ACB301, targetNamespace = targetNamespaceStr) String aab301);

	/**
	 * 
	 * @param aac003
	 * @param aab301
	 * @param user
	 * @param aac002
	 * @param pass
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "getAZ03Return", targetNamespace = targetNamespaceStr)
	@RequestWrapper(localName = "getAZ03", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.GetAZ03")
	@ResponseWrapper(localName = "getAZ03Response", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.GetAZ03Response")
	String getAZ03(
			@WebParam(name = USERSTR, targetNamespace = targetNamespaceStr) String user,
			@WebParam(name = PASS, targetNamespace = targetNamespaceStr) String pass,
			@WebParam(name = ACC002, targetNamespace = targetNamespaceStr) String aac002,
			@WebParam(name = ACC003, targetNamespace = targetNamespaceStr) String aac003,
			@WebParam(name = ACB301, targetNamespace = targetNamespaceStr) String aab301);

	/**
	 * 
	 * @param aac003
	 * @param aab301
	 * @param user
	 * @param aac002
	 * @param pass
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "getAC01Return", targetNamespace = targetNamespaceStr)
	@RequestWrapper(localName = "getAC01", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.GetAC01")
	@ResponseWrapper(localName = "getAC01Response", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.GetAC01Response")
	String getAC01(
			@WebParam(name = USERSTR, targetNamespace = targetNamespaceStr) String user,
			@WebParam(name = PASS, targetNamespace = targetNamespaceStr) String pass,
			@WebParam(name = ACC002, targetNamespace = targetNamespaceStr) String aac002,
			@WebParam(name = ACC003, targetNamespace = targetNamespaceStr) String aac003,
			@WebParam(name = ACB301, targetNamespace = targetNamespaceStr) String aab301);

	/**
	 * 
	 * @param dodebit
	 * @param aab301A
	 * @param user
	 * @param pass
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "checkTACReturn", targetNamespace = targetNamespaceStr)
	@RequestWrapper(localName = "checkTAC", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.CheckTAC")
	@ResponseWrapper(localName = "checkTACResponse", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.CheckTACResponse")
	String checkTAC(
			@WebParam(name = USERSTR, targetNamespace = targetNamespaceStr) String user,
			@WebParam(name = PASS, targetNamespace = targetNamespaceStr) String pass,
			@WebParam(name = "dodebit", targetNamespace = targetNamespaceStr) String dodebit,
			@WebParam(name = "aab301a", targetNamespace = targetNamespaceStr) String aab301A);

	/**
	 * 
	 * @param id
	 * @param aab301
	 * @param user
	 * @param pass
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "readCardReturn", targetNamespace = targetNamespaceStr)
	@RequestWrapper(localName = "readCard", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.ReadCard")
	@ResponseWrapper(localName = "readCardResponse", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.ReadCardResponse")
	String readCard(
			@WebParam(name = USERSTR, targetNamespace = targetNamespaceStr) String user,
			@WebParam(name = PASS, targetNamespace = targetNamespaceStr) String pass,
			@WebParam(name = "id", targetNamespace = targetNamespaceStr) String id,
			@WebParam(name = ACB301, targetNamespace = targetNamespaceStr) String aab301);

	/**
	 * 
	 * @param xml
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "allDsjkReturn", targetNamespace = targetNamespaceStr)
	@RequestWrapper(localName = "allDsjk", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.AllDsjk")
	@ResponseWrapper(localName = "allDsjkResponse", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.AllDsjkResponse")
	String allDsjk(
			@WebParam(name = "xml", targetNamespace = targetNamespaceStr) String xml);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "getCardInfoReturn", targetNamespace = targetNamespaceStr)
	@RequestWrapper(localName = "getCardInfo", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.GetCardInfo")
	@ResponseWrapper(localName = "getCardInfoResponse", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.GetCardInfoResponse")
	String getCardInfo();

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "getSockInfoReturn", targetNamespace = targetNamespaceStr)
	@RequestWrapper(localName = "getSockInfo", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.GetSockInfo")
	@ResponseWrapper(localName = "getSockInfoResponse", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.GetSockInfoResponse")
	String getSockInfo();

	/**
	 * 
	 * @param dodebit
	 * @param aab301A
	 * @param user
	 * @param pass
	 */
	@WebMethod
	@RequestWrapper(localName = "checkTAC1", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.CheckTAC1")
	@ResponseWrapper(localName = "checkTAC1Response", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.CheckTAC1Response")
	void checkTAC1(
			@WebParam(name = USERSTR, targetNamespace = targetNamespaceStr) String user,
			@WebParam(name = PASS, targetNamespace = targetNamespaceStr) String pass,
			@WebParam(name = "dodebit", targetNamespace = targetNamespaceStr) String dodebit,
			@WebParam(name = "aab301a", targetNamespace = targetNamespaceStr) String aab301A);

	/**
	 * 
	 * @param aac003
	 * @param aab301
	 * @param user
	 * @param aac002
	 * @param pass
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "getDataReturn", targetNamespace = targetNamespaceStr)
	@RequestWrapper(localName = "getData", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.GetData")
	@ResponseWrapper(localName = "getDataResponse", targetNamespace = targetNamespaceStr, className = "cn.com.qytx.webservice.impl.GetDataResponse")
	String getData(
			@WebParam(name = USERSTR, targetNamespace = targetNamespaceStr) String user,
			@WebParam(name = PASS, targetNamespace = targetNamespaceStr) String pass,
			@WebParam(name = ACC002, targetNamespace = targetNamespaceStr) String aac002,
			@WebParam(name = ACC003, targetNamespace = targetNamespaceStr) String aac003,
			@WebParam(name = ACB301, targetNamespace = targetNamespaceStr) String aab301);

}
