/* 危险源表 */
CREATE TABLE "AH_USER_V2"."TB_DANGER_SOURCE"
  (
    "ID"                 NUMBER(10,0) NOT NULL ENABLE,
    "DANGER_SOURCE_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
    "REGION_ID"          NUMBER(10,0) NOT NULL ENABLE,
    "COMPANY_ID"         NUMBER(10,0) NOT NULL ENABLE,
    "DANGER_LEVEL"       NUMBER(2,0) NOT NULL ENABLE,
    "R_VALUE"            NUMBER(10,0) NOT NULL ENABLE,
    "EVALUTE_ORG"        VARCHAR2(100 BYTE),
    "EVALUTE_TIME" DATE,
    "BEGIN_USE_TIME" DATE,
    "ADDRESS"               VARCHAR2(200 BYTE) NOT NULL ENABLE,
    "LATITUDE"              NUMBER(10,6),
    "LONGITUDE"             NUMBER(10,6),
    "PRODUCT_SCALE"         VARCHAR2(500 BYTE) NOT NULL ENABLE,
    "INDUSTRY_AREA_ID"      NUMBER(10,0),
    "MIN_DISTANCE"          NUMBER(10,2) NOT NULL ENABLE,
    "ESTIMATE_PEOPLE_COUNT" NUMBER(10,0),
    "ACCIDENT_DESC"         VARCHAR2(500 BYTE) NOT NULL ENABLE,
    "CREATE_TIME" DATE NOT NULL ENABLE,
    "CREATE_USER_ID" NUMBER(10,0) NOT NULL ENABLE,
    "LAST_UPDATE_TIME" DATE,
    "LAST_UPDATE_USER_ID" NUMBER(10,0),
    "IS_DELETE"           NUMBER(1,0) NOT NULL ENABLE,
    "IS_FORK_GROUP"       NUMBER(10,0) NOT NULL ENABLE,
    CONSTRAINT "TB_DANGER_SOURCE_PK" PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "AH_DATA_V2" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "AH_DATA_V2" ;
COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."ID"
IS
  '主键';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."DANGER_SOURCE_NAME"
IS
  '危险源名称';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."REGION_ID"
IS
  '县区ID';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."COMPANY_ID"
IS
  '企业id';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."DANGER_LEVEL"
IS
  '危险源级别（一级1、二级2、三级3、四级4、其他10）';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."R_VALUE"
IS
  '危险源R值';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."EVALUTE_ORG"
IS
  '评价机构';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."EVALUTE_TIME"
IS
  '最新评价时间';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."BEGIN_USE_TIME"
IS
  '投用日期';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."ADDRESS"
IS
  '重大危险源所在地址';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."LATITUDE"
IS
  '纬度';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."LONGITUDE"
IS
  '经度';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."PRODUCT_SCALE"
IS
  '生产规模';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."INDUSTRY_AREA_ID"
IS
  '工业园区id';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."MIN_DISTANCE"
IS
  '最近防护距离';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."ESTIMATE_PEOPLE_COUNT"
IS
  '500米范围内人数估算值';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."ACCIDENT_DESC"
IS
  '近三年事故情况';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."CREATE_TIME"
IS
  '创建时间';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."CREATE_USER_ID"
IS
  '创建人';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."LAST_UPDATE_TIME"
IS
  '最后修改时间';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."LAST_UPDATE_USER_ID"
IS
  '最后修改人';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."IS_DELETE"
IS
  '是否删除(0否， 1是)';
  COMMENT ON COLUMN "AH_USER_V2"."TB_DANGER_SOURCE"."IS_FORK_GROUP"
IS
  '数据权限';


/* 危险源列表菜单 */
insert into tb_module_info(module_id, is_delete, module_class, module_code, module_level, module_name, module_type, order_index, parent_id, sys_name, url, default_state, menu_type) 
  values(2680401, 0, 'osm_ErrorSourceManage', 'osm_ESM_Collect', 3, '危险源管理', 1, 1, 26804, 'osm_OnlineManage', 'wh/logined/dangersource/dangerSourceList.jsp', 1, 1);


/* 传感器列表菜单 */
insert into tb_module_info(module_id, is_delete, module_class, module_code, module_level, module_name, module_type, order_index, parent_id, sys_name, url, default_state, menu_type) 
  values(2680402, 0, 'osm_ErrorSourceManage', 'osm_ESM_Collectsensor', 3, '传感器管理', 1, 2, 26804, 'osm_OnlineManage', 'wh/logined/collectsensor/collectsensor.jsp', 1, 1);
  
/*  */

